steps:
- id: "Instalando"
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'hello']
  env: ['GOPATH=.']

- id: "Teste unitário"
  name: 'gcr.io/cloud-builders/go'
  args: ['test','hello']
  env: ['GOPATH=.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=marcosbacci/k8s', '.']

images:
- 'marcosbacci/k8s'
