apiVersion: apps/v1
kind: Deployment
metadata:
        name: hello-go
spec:
        selector:
                matchLabels:
                        app: hello-go
        template:
               metadata:
                       labels:
                            app: hello-go
               spec:
                       containers:
                       - name: go
                         image: marcosbacci/k8s:latest
                         ports:
                         - containerPort: 8000
