FROM golang:alpine AS builder
RUN apk update && apk add --no-cache git

WORKDIR $GOPATH/src/helloworld/

COPY *.go .

ENV CGO_ENABLED 0
RUN go get -d -v
RUN go build -ldflags="-s -w" -o /go/bin/hello

FROM scratch

COPY --from=builder /go/bin/hello /go/bin/hello

EXPOSE 8000

ENTRYPOINT ["/go/bin/hello"]

#ENTRYPOINT ["go", "run", "main.go"]
