FROM golang:alpine AS builder
RUN apk update && apk add --no-cache git

WORKDIR $GOPATH/src/helloworld/hello

COPY src/hello/*.go .

ENV CGO_ENABLED 0
RUN go get -d -v
RUN go build -ldflags="-s -w" -o /go/bin

FROM scratch

COPY --from=builder /go/bin/hello /hello

EXPOSE 8000

ENTRYPOINT ["/hello"]

#ENTRYPOINT ["go", "run", "main.go"]
